# Generated by Django 5.0.6 on 2024-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('recurrente', models.BooleanField(default=False)),
                ('duracion', models.PositiveIntegerField(blank=True, null=True)),
                ('unidad_duracion', models.CharField(blank=True, choices=[('D', 'Días'), ('S', 'Semanas'), ('M', 'Meses'), ('A', 'Años')], max_length=1, null=True)),
            ],
        ),
    ]
