# Generated by Django 5.0.6 on 2024-07-01 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('pago_fraccionado', models.BooleanField(default=False)),
                ('duracion_fraccionada', models.PositiveIntegerField(blank=True, null=True)),
                ('unidad_duracion_fraccionada', models.CharField(blank=True, choices=[('D', 'Días'), ('S', 'Semanas'), ('M', 'Meses'), ('A', 'Años')], max_length=1, null=True)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programas.programa')),
            ],
        ),
    ]
